### ISSUE TITLE
generates metasploit payload, generate backdoors not working?

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [veerupandey/Penetration-Testing-Toolkit#2]
Hello.

I have problem with generates metasploit payload and backdoors. When job finish and click link for DOWNLOAD get error 404 Not Found (because files not in folder!)

It is working or not?

**Comment by 15w34r0n3D4y** [comment]
Terminal not works

DDOS Javascript (website not found)

and other function not tested yet but I think it's not working...

**Comment by veerupandey** [comment]
1. For terminal to work:
   sudo apt-get install shellinabox 
2. DDos JavaScript will not work because Ubuntu One is closed now(file was hosted here)

3.Please check whether the metasploit is working properly before generating the payload or backdoors.

Thanks

**Comment by 15w34r0n3D4y** [comment]
Sorry my mistake I forget add user 'www-data' into /etc/sudoers file 

Thank you
